<!--<h2>Hot Products</h2>-->

 <?php if ( sizeof($this->resultado) ):  ?>

    <?php foreach ( $resultado as $produto ) : ?>

        
        <ul class="thumbnails">
            <li class="span3">
                <div class="thumbnail">
                    <img alt="" src="<?php echo $produto->ds_endereco_img_produto ?>">
                    <div class="caption">
                        <h5><?php echo $produto->nm_produto ?></h5>
                        <p>
                            <a class="btn primary details" href="#" rel="ajax/1.html">
                                <i class="icon-zoom-in"></i>
                            </a> 
                            <a class="btn addto" href="#" rel="1">Comprar <i class="icon-shopping-cart"></i></a> 
                            <span class="label label-info price">R$<?php echo $produto->vlr_produto ?> </span>
                        </p>

                    </div>
                </div>
            </li>
        </ul>

    <?php endforeach; ?>

<?php endif; ?>  

<!--<ul class="thumbnails">
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/1.jpg">
            <div class="caption">
                <h5>Item 1</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/1.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="1">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 10</span></p>

            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/2.jpg">
            <div class="caption">
                <h5>Item 2</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/2.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="2">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 15</span></p>
            </div>
        </div>
    </li>                        
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/3.jpg">
            <div class="caption">
                <h5>Item 3</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/3.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="3">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 5</span></p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/4.jpg">
            <div class="caption">
                <h5>Item 4</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/4.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="4">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 33</span></p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/5.jpg">
            <div class="caption">
                <h5>Item 5</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/5.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="5">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 6</span></p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/6.jpg">
            <div class="caption">
                <h5>Item 6</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/6.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="6">Add to <i class="icon-shopping-cart"></i></a>  <span class="label label-info price">$ 41</span></p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/7.jpg">
            <div class="caption">
                <h5>Item 7</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/7.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="7">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 9.99</span></p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/8.jpg">
            <div class="caption">
                <h5>Item 8</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/8.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="8">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 3.16</span></p>
            </div>
        </div>
    </li>
    <li class="span3">
        <div class="thumbnail">
            <img alt="" src="img/9.jpg">
            <div class="caption">
                <h5>Item 9</h5>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn primary details" href="#" rel="ajax/9.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="9">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price">$ 8</span></p>
            </div>
        </div>
    </li>
</ul>
<div class="pagination">
    <ul>
        <li><a href="#">Prev</a></li>
        <li class="active">
            <a href="#">1</a>
        </li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>-->
